<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://example" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://example" xmlns:intf="http://example" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://example" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="testReturn" type="xsd:string"/>
  </schema>
 </wsdl:types>

   <wsdl:message name="testResponse">

      <wsdl:part element="impl:testReturn" name="testReturn"/>

   </wsdl:message>

   <wsdl:message name="testRequest">

   </wsdl:message>

   <wsdl:portType name="Test">

      <wsdl:operation name="test">

         <wsdl:input message="impl:testRequest" name="testRequest"/>

         <wsdl:output message="impl:testResponse" name="testResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TestSoapBinding" type="impl:Test">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="test">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="testRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="testResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TestService">

      <wsdl:port binding="impl:TestSoapBinding" name="Test">

         <wsdlsoap:address location="http://localhost:8080//services/example/Test"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
